using RaccoonNinja.McpToolset.Server.FileVault.Domain;
using RaccoonNinja.McpToolset.Server.FileVault.Services;
using RaccoonNinja.McpToolset.Server.FileVault.Storage;

namespace RaccoonNinja.McpToolset.Server.FileVault.Tests.Storage;

/// <summary>
/// Store-compatibility tests: open a store written by the REAL Rust vault-mcp binary (the
/// committed fixture under <c>Fixtures/rust-store</c>, generated by
/// <c>Fixtures/generate-rust-fixture.ps1</c>) and prove reads, listings, and writes work with no
/// data loss and no schema divergence. Each test works on a fresh copy of the fixture.
/// </summary>
public sealed class StoreCompatTests : IDisposable
{
    private readonly string _home;
    private readonly SqliteConnectionFactory _factory;
    private readonly VaultService _service;
    private readonly int _migrationsApplied;

    public StoreCompatTests()
    {
        var fixture = Path.Combine(AppContext.BaseDirectory, "Fixtures", "rust-store");
        Assert.SkipUnless(
            File.Exists(Path.Combine(fixture, "vault.db")),
            "Rust-written fixture missing; run tests/…/Fixtures/generate-rust-fixture.ps1 first.");

        // Work on a copy: compat tests write to the store, and the committed fixture must stay
        // byte-for-byte what the Rust binary produced.
        _home = Path.Combine(Path.GetTempPath(), "filevault-tests", Guid.NewGuid().ToString("N"));
        CopyTree(fixture, _home);

        var config = SqliteVaultRepositoryTests.TestConfig(_home);
        _factory = new SqliteConnectionFactory(config);
        _migrationsApplied = Migrator.Run(_factory);
        _service = new VaultService(new SqliteVaultRepository(_factory), new FileStore(config.FilesDir), config);
    }

    public void Dispose()
    {
        Microsoft.Data.Sqlite.SqliteConnection.ClearAllPools();
        if (_home is not null && Directory.Exists(_home))
        {
            try
            {
                Directory.Delete(_home, recursive: true);
            }
            catch (IOException)
            {
                // Best-effort temp cleanup.
            }
        }
    }

    [Fact]
    public void Open_RustWrittenStore_RequiresNoNewMigrations()
    {
        // Assert
        Assert.Equal(0, _migrationsApplied);
        using var connection = _factory.Open();
        Assert.Equal(2, Migrator.CurrentVersion(connection));
    }

    [Fact]
    public void Get_RustWrittenVersions_ReadBackWithHistoryAndLiveSummary()
    {
        // Act
        var project = ProjectName.Parse("fixture");
        var name = FileName.Parse("multi-version");
        var (record, content, _) = _service.Get(project, name, version: null);
        var v1 = _service.Get(project, name, version: 1);
        var history = _service.History(project, name);

        // Assert
        Assert.Equal(3, record.CurrentVersion);
        Assert.Equal("alpha\nbeta\ngamma\n", content);
        Assert.Equal("live summary after set_meta", record.Summary);
        Assert.Equal(["kind-b"], record.Tags);
        Assert.Equal("alpha\n", v1.Content);
        Assert.Equal("first version", v1.Record.Summary);
        Assert.Equal([3, 2, 1], history.Select(h => h.Version));
        Assert.Equal(VaultOp.Append, history[0].Op);
    }

    [Fact]
    public void Get_RustWrittenHashes_MatchRecomputedBlake3()
    {
        // Act
        var (record, content, _) = _service.Get(ProjectName.Parse("fixture"), FileName.Parse("multi-version"), null);

        // Assert
        Assert.Equal(record.Hash.Hex, ContentHash.OfText(content).Hex);
        Assert.Contains(record.Hash.ShortHex, record.RelPath);
    }

    [Fact]
    public void Get_RustWrittenUnicodeContent_SurvivesByteForByte()
    {
        // Act
        var (_, content, _) = _service.Get(ProjectName.Parse("fixture"), FileName.Parse("unicode-note"), null);

        // Assert
        Assert.Equal("emoji 🦝 and 中文テキスト\n", content);
    }

    [Fact]
    public void Get_RustWrittenHierarchy_ExposesParentAndChildren()
    {
        // Act
        var parent = _service.Get(ProjectName.Parse("fixture"), FileName.Parse("parent-note"), null);
        var child = _service.Get(ProjectName.Parse("fixture"), FileName.Parse("child-note"), null);

        // Assert
        Assert.Equal("parent-note", child.Record.Parent);
        var onlyChild = Assert.Single(parent.Children);
        Assert.Equal("child-note", onlyChild.Name);
    }

    [Fact]
    public void List_RustWrittenStore_HidesArchivedAndSearchesFts()
    {
        // Act
        var all = _service.List(ProjectName.Parse("fixture"), tags: null, query: null);
        var archived = _service.Get(ProjectName.Parse("fixture"), FileName.Parse("archived-note"), null);
        var byQuery = _service.List(project: null, tags: null, query: "slash");

        // Assert
        Assert.DoesNotContain("archived-note", all.Select(r => r.Name));
        Assert.Equal(FileState.Archived, archived.Record.State);
        var onlyMatch = Assert.Single(byQuery);
        Assert.Equal("mono/app", onlyMatch.Project);
    }

    [Fact]
    public void Save_IntoRustWrittenStore_CommitsNextVersionInRustShape()
    {
        // Act
        var committed = _service.Save(
            ProjectName.Parse("fixture"), FileName.Parse("multi-version"), "alpha\nbeta\ngamma\ndelta\n",
            "fourth, from csharp", baseVersion: 3, tags: null, VaultFormat.Text, ParentUpdate.Leave);

        // Assert
        Assert.Equal(4, committed.Version);
        var (record, content, _) = _service.Get(ProjectName.Parse("fixture"), FileName.Parse("multi-version"), null);
        Assert.EndsWith("delta\n", content);
        Assert.Equal($"fixture/multi-version/v0004-{committed.Hash.ShortHex}.txt", record.RelPath);
        using var connection = _factory.Open();
        Assert.Equal(2, Migrator.CurrentVersion(connection));
    }

    private static void CopyTree(string source, string destination)
    {
        Directory.CreateDirectory(destination);
        foreach (var directory in Directory.GetDirectories(source, "*", SearchOption.AllDirectories))
        {
            Directory.CreateDirectory(Path.Combine(destination, Path.GetRelativePath(source, directory)));
        }

        foreach (var file in Directory.GetFiles(source, "*", SearchOption.AllDirectories))
        {
            File.Copy(file, Path.Combine(destination, Path.GetRelativePath(source, file)));
        }
    }
}